app:
  name: elk-mall
  version: 1.0.0

server:
  http_port: 8080
  log_level: debug # debug / info / warn / error
  env: prod # local -> 开发环境；prod -> 生产环境
  enable_pprof: false # 是否启用 pprof

mysql:
  dialect: mysql # mysql / sqlite3 / postgres
  user: root # 用户名
  password: root # 密码
  host: 127.0.0.1 # 主机
  port: 3308 # 端口
  database: elk_mall # 数据库
  charset: utf8mb4 # 字符集
  show_sql: true # 是否显示 SQL
  max_open: 20 # 最大连接数
  max_idle: 5 # 最大空闲连接数

redis:
  addr: 127.0.0.1:6380 # 地址
  password: "" # 密码
  db: 0 # 数据库索引
  max_idle: 10 # 最大空闲连接数
  max_open: 100 # 最大连接数

  